# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
pod 'Firebase/Core', '~> 5.15.0'

target 'ThundrVoice' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ThundrVoice

  target 'ThundrVoiceTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ThundrVoice-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ThundrVoice-tvOS

  target 'ThundrVoice-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
