# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
pod 'Firebase/Core'

target 'Thundr' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Thundr

  # target 'Thundr-tvOSTests' do
    # inherit! :search_paths
    # Pods for testing
  # end

  target 'ThundrTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# target 'Thundr-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Thundr-tvOS

  # target 'Thundr-tvOSTests' do
    # inherit! :search_paths
    # Pods for testing
  # end

# end
